apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: online-boutique-frontend
  namespace: default
spec:
  interval: 5m
  url: https://github.com/bmuschko/google-online-boutique-frontend-deploy
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: online-boutique-frontend
  namespace: default
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: online-boutique-frontend
  path: "./kustomize"
  prune: true
  timeout: 1m